### ISSUE TITLE
[META 27] Add ecs-logging-php to the doc build

### ISSUE THREAD

**Issue by bmorelli25** [elastic/ecs-logging-php#20]
## To do

- [x] Move docs to asciidoc https://github.com/elastic/ecs-logging-php/pull/18
- [x] Open PR in `elastic/docs` to add to the build https://github.com/elastic/docs/pull/2055
- [x] Open infra ticket to add the `elasticsearch/ci docs` check to this repo (see link in timeline below)
- [x] Add the `elasticsearch/ci docs` webhook to the repo
- [x] Remove content from readme and link to published docs https://github.com/elastic/ecs-logging-php/pull/21
- [x] Link to new docs from ecs-logging https://github.com/elastic/ecs-logging/pull/53

**Comment by bmorelli25** [comment]
Docs are live: https://www.elastic.co/guide/en/ecs-logging/php/current/index.html
